// 진호 OS — sample transactions (mock mode 기본값)
// 마스킹된 가상 데이터. 실제 카드번호/계좌번호/토큰 포함 금지.
// 합계가 기존 moneyKpi 와 정합되도록 의도적으로 design — UI 표시값이 변하지 않게 한다.

import type { Transaction } from "./types";

// 6개월 trend (만원 단위) — moneyKpi.trend 와 정확히 일치
// 이 배열은 외부 입력 (toss/banksalad export) 으로 교체될 수 있음.
export const MONTHLY_TOTALS_MAN_WON: Array<{ month: string; total_man: number }> = [
  { month: "2025-12", total_man: 310 },
  { month: "2026-01", total_man: 285 },
  { month: "2026-02", total_man: 332 },
  { month: "2026-03", total_man: 298 },
  { month: "2026-04", total_man: 365 },
  { month: "2026-05", total_man: 284 },
];

// 2026-05 (이번 달) 거래 샘플 — 합계 2,843,000 = moneyKpi.spent
// 카테고리별 합계도 moneyKpi.topCategories 와 정합.
// 익명화 위해 카드번호/이메일/주소 등 절대 포함 금지.
export const SAMPLE_TRANSACTIONS: Transaction[] = [
  // ── 큰 거래 4건 (bigTransactions 에 그대로 노출) ──
  {
    id: "tx-edid-popup",
    date: "2026-05-08",
    vendor: "EDID",
    amount: 500_000,
    currency: "KRW",
    category: "Commerce",
    subcategory: "팝업/리테일",
    business_or_personal: "biz",
    recurring: false,
    source: "mock",
    source_email_subject: "EDID 성수 팝업 보증금 입금 확인",
    raw_text: "EDID 성수 팝업 보증금 ₩500,000",
    created_at: "2026-05-08T16:02:00+09:00",
  },
  {
    id: "tx-team-dinner-han",
    date: "2026-05-06",
    vendor: "한정식 식당",
    amount: 287_000,
    currency: "KRW",
    category: "Team Ops",
    subcategory: "회식",
    business_or_personal: "personal", // 기존 KPI 가 personal 로 잡혀있어 유지
    recurring: false,
    source: "mock",
    source_email_subject: undefined,
    raw_text: "팀 회식 (한정식) ₩287,000",
    created_at: "2026-05-06T20:48:00+09:00",
  },
  {
    id: "tx-chatgpt-pro",
    date: "2026-05-03",
    vendor: "ChatGPT Pro",
    amount: 270_000,
    currency: "KRW",
    category: "AI/LLM",
    subcategory: "Subscription",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[OpenAI] Your ChatGPT Pro renewal — $200.00",
    raw_text: "ChatGPT Pro renewal $200 (환산 ₩270,000)",
    original_amount: 200,
    original_currency: "USD",
    created_at: "2026-05-03T08:01:00+09:00",
  },

  // ── AI/LLM 카테고리 보강 (Top 487,000 맞춤: 위 270,000 + 아래 217,000) ──
  {
    id: "tx-anthropic-may",
    date: "2026-05-10",
    vendor: "Anthropic",
    amount: 134_000,
    currency: "KRW",
    category: "AI/LLM",
    subcategory: "API",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[Anthropic] Usage invoice — $97.10",
    raw_text: "Anthropic API May usage $97.10",
    original_amount: 97.1,
    original_currency: "USD",
    created_at: "2026-05-10T10:00:00+09:00",
  },
  {
    id: "tx-openai-may",
    date: "2026-05-11",
    vendor: "OpenAI",
    amount: 83_000,
    currency: "KRW",
    category: "AI/LLM",
    subcategory: "API",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[OpenAI] Usage receipt — $60.14",
    raw_text: "OpenAI API May usage $60.14",
    original_amount: 60.14,
    original_currency: "USD",
    created_at: "2026-05-11T10:00:00+09:00",
  },

  // ── Infra/VPS Top 198,000 ──
  {
    id: "tx-hostinger",
    date: "2026-05-01",
    vendor: "Hostinger",
    amount: 28_000,
    currency: "KRW",
    category: "Infra/VPS",
    subcategory: "VPS",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[Hostinger] VPS monthly invoice",
    raw_text: "Hostinger KVM 4 ₩28,000/mo",
    created_at: "2026-05-01T03:00:00+09:00",
  },
  {
    id: "tx-cloudflare",
    date: "2026-05-02",
    vendor: "Cloudflare",
    amount: 27_000,
    currency: "KRW",
    category: "Infra/VPS",
    subcategory: "CDN/DNS",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[Cloudflare] Receipt — $20.00",
    raw_text: "Cloudflare Pro $20",
    original_amount: 20,
    original_currency: "USD",
    created_at: "2026-05-02T05:00:00+09:00",
  },
  {
    id: "tx-supabase",
    date: "2026-05-04",
    vendor: "Supabase",
    amount: 35_000,
    currency: "KRW",
    category: "Infra/VPS",
    subcategory: "DB",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[Supabase] Receipt — $25.00",
    raw_text: "Supabase Pro $25",
    original_amount: 25,
    original_currency: "USD",
    created_at: "2026-05-04T05:00:00+09:00",
  },
  {
    id: "tx-vercel",
    date: "2026-05-05",
    vendor: "Vercel",
    amount: 28_000,
    currency: "KRW",
    category: "Infra/VPS",
    subcategory: "Hosting",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[Vercel] Receipt — $20.00",
    raw_text: "Vercel Pro $20",
    original_amount: 20,
    original_currency: "USD",
    created_at: "2026-05-05T05:00:00+09:00",
  },
  {
    id: "tx-aws-misc",
    date: "2026-05-07",
    vendor: "AWS",
    amount: 80_000,
    currency: "KRW",
    category: "Infra/VPS",
    subcategory: "Cloud",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[AWS] Invoice",
    raw_text: "AWS Misc storage/egress",
    original_amount: 58,
    original_currency: "USD",
    created_at: "2026-05-07T05:00:00+09:00",
  },

  // ── Team Ops Top 412,000 (회식 287k 위에 포함, +125k) ──
  {
    id: "tx-office-supplies",
    date: "2026-05-09",
    vendor: "사무용품",
    amount: 125_000,
    currency: "KRW",
    category: "Team Ops",
    subcategory: "오피스",
    business_or_personal: "biz",
    recurring: false,
    source: "mock",
    raw_text: "사무실 비품 보충 ₩125,000",
    created_at: "2026-05-09T13:21:00+09:00",
  },

  // ── 식비/외식 Top 612,000 (개인) ──
  {
    id: "tx-food-1",
    date: "2026-05-02",
    vendor: "배달의민족",
    amount: 184_000,
    currency: "KRW",
    category: "Food/Meeting",
    subcategory: "외식/배달",
    business_or_personal: "personal",
    recurring: false,
    source: "mock",
    raw_text: "5월 1-2주 배달 누적",
    created_at: "2026-05-02T20:00:00+09:00",
  },
  {
    id: "tx-food-2",
    date: "2026-05-09",
    vendor: "스타벅스",
    amount: 96_000,
    currency: "KRW",
    category: "Food/Meeting",
    subcategory: "카페",
    business_or_personal: "personal",
    recurring: false,
    source: "mock",
    raw_text: "5월 카페 누적",
    created_at: "2026-05-09T11:00:00+09:00",
  },
  {
    id: "tx-food-3",
    date: "2026-05-11",
    vendor: "외식",
    amount: 332_000,
    currency: "KRW",
    category: "Food/Meeting",
    subcategory: "외식",
    business_or_personal: "personal",
    recurring: false,
    source: "mock",
    raw_text: "5월 1-2주 외식 누적",
    created_at: "2026-05-11T19:30:00+09:00",
  },

  // ── 교통 Top 312,000 (개인) ──
  {
    id: "tx-transport-1",
    date: "2026-05-03",
    vendor: "카카오 T",
    amount: 168_000,
    currency: "KRW",
    category: "Personal",
    subcategory: "교통",
    business_or_personal: "personal",
    recurring: false,
    source: "mock",
    raw_text: "택시 누적",
    created_at: "2026-05-03T18:00:00+09:00",
  },
  {
    id: "tx-transport-2",
    date: "2026-05-07",
    vendor: "KTX/SRT",
    amount: 144_000,
    currency: "KRW",
    category: "Personal",
    subcategory: "교통",
    business_or_personal: "personal",
    recurring: false,
    source: "mock",
    raw_text: "출장 KTX 왕복",
    created_at: "2026-05-07T07:00:00+09:00",
  },

  // ── 건강/운동 Top 245,000 (개인) ──
  {
    id: "tx-gym",
    date: "2026-05-01",
    vendor: "필라테스",
    amount: 245_000,
    currency: "KRW",
    category: "Personal",
    subcategory: "건강/운동",
    business_or_personal: "personal",
    recurring: true,
    source: "mock",
    raw_text: "필라테스 월회비",
    created_at: "2026-05-01T07:00:00+09:00",
  },

  // ── Other (Top 6 외) — 합계 577,000 ──
  // EDID 500k (Commerce, big tx에 노출) + Notion 12k + 미분류 65k
  {
    id: "tx-notion",
    date: "2026-05-02",
    vendor: "Notion",
    amount: 12_000,
    currency: "KRW",
    category: "SaaS/Subscription",
    subcategory: "Productivity",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[Notion] Receipt",
    raw_text: "Notion ₩12,000/mo",
    created_at: "2026-05-02T05:00:00+09:00",
  },
  {
    id: "tx-misc-1",
    date: "2026-05-13",
    vendor: "기타",
    amount: 65_000,
    currency: "KRW",
    category: "Unknown",
    subcategory: "미분류",
    business_or_personal: "personal",
    recurring: false,
    source: "mock",
    raw_text: "5월 미분류 기타",
    created_at: "2026-05-13T15:00:00+09:00",
  },
];


// 분기/연 결제 — UI 의 bigTransactions 에는 표시하지만 월별 spent 합계에는 포함시키지 않음.
// (회계상 prepaid expense — 매월 amortize 하지 않으면 결제월에 spent 가 비정상적으로 부풀음)
export const LUMP_SUM_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-modash-q2",
    date: "2026-05-12",
    vendor: "Modash",
    amount: 1_682_000,
    currency: "KRW",
    category: "SaaS/Subscription",
    subcategory: "Creator-DB",
    business_or_personal: "biz",
    recurring: true,
    source: "mock",
    source_email_subject: "[Modash] Q2 2026 invoice — paid",
    raw_text: "Modash Q2 invoice $1,240 (분기 결제, 환산 ₩1,682,000)",
    original_amount: 1240,
    original_currency: "USD",
    created_at: "2026-05-12T09:14:00+09:00",
  },
];

// /money 페이지의 "구독" 카드 표시용 — 카드/벤더별 월 환산
// 표시문구는 기존 mockData 와 동일하게 유지.
export const SAMPLE_SUBSCRIPTIONS: Array<{
  name: string;
  amount: string;
  kind: "biz" | "personal";
  monthly: number;
}> = [
  { name: "Anthropic API", amount: "변동", kind: "biz", monthly: 180_000 },
  { name: "OpenAI API", amount: "변동", kind: "biz", monthly: 120_000 },
  { name: "ChatGPT Pro", amount: "$200", kind: "biz", monthly: 270_000 },
  { name: "Hostinger VPS", amount: "₩28k/mo", kind: "biz", monthly: 28_000 },
  { name: "Cloudflare", amount: "$20", kind: "biz", monthly: 27_000 },
  { name: "Notion", amount: "₩12k/mo", kind: "biz", monthly: 12_000 },
  { name: "Modash", amount: "$1,240/Q", kind: "biz", monthly: 560_000 },
];
